import {CONFIG,TEMPLATES,DEFAULT_MESSAGES,ROUTES} from './data.js';
import {storage} from './storage.js';
import {cloudList,cloudUpsert,cloudDelete,cloudStatus} from './cloud.js';
import {paper,plainText,recordFromState,validate,get,dateText} from './document.js';

const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={route:'home',tab:'identity',template:'sponsorship',size:'a4',number:'',id:'',zoom:CONFIG.zoom.default,digitalStamp:true,recipient:'',recipientName:'',date:'',eventName:'',extraParam:'',value:'',message:'',prName:'',prContact:'',prEmail:''};
let records=[];let saveTimer;let cloudReady=false;
const fieldIds=['recipient','recipientName','date','eventName','extraParam','value','message','prName','prContact','prEmail'];
const clone=x=>JSON.parse(JSON.stringify(x));
const today=()=>new Date().toISOString().slice(0,10);
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2400)}
function applyTheme(choice=localStorage.getItem(CONFIG.themeKey)||'system'){document.body.classList.toggle('light',choice==='light'||(choice==='system'&&matchMedia('(prefers-color-scheme:light)').matches));localStorage.setItem(CONFIG.themeKey,choice);$$('[data-theme-choice]').forEach(b=>b.classList.toggle('active',b.dataset.themeChoice===choice))}
function syncUI(){const text=cloudReady?'متزامن مع السحابة':'التخزين المحلي';$('#syncTitle').textContent=text;$('#syncText').textContent=cloudReady?'حفظ ومزامنة مفعلة':'البيانات محفوظة على جهازك';$('#saveState label').textContent=cloudReady?'متزامن':'محلي';$('#saveState span').style.background=cloudReady?'#34d399':'#fbbf24';$('#statCloud')&&($('#statCloud').textContent=cloudReady?'متزامن':'محلي');$('#navCount')&&($('#navCount').textContent=records.length)}
function setRoute(route){state.route=ROUTES[route]?route:'home';location.hash=state.route;renderRoute()}
function renderRoute(){const route=state.route;$('#pageTitle').textContent=ROUTES[route];$$('.nav-item[data-route]').forEach(x=>x.classList.toggle('active',x.dataset.route===route));const tpl=$(`#${route}Template`);if(!tpl){return}$('#view').replaceChildren(tpl.content.cloneNode(true));if(route==='home')renderHome();if(route==='create')initCreate();if(route==='library')initLibrary();if(route==='templates')initTemplates();if(route==='settings')initSettings();closeMobile()}
function renderHome(){const year=new Date().getFullYear();$('#statTotal').textContent=records.length;$('#statYear').textContent=records.filter(r=>String(get(r,'date')).startsWith(String(year))).length;$('#statYearLabel').textContent=year;$('#statTemplate').textContent=records[0]?TEMPLATES[records[0].template]?.name||'—':'—';const recent=$('#recentList');recent.innerHTML='';if(!records.length){recent.innerHTML='<div class="empty">لا توجد خطابات محفوظة حتى الآن</div>'}else records.slice(0,5).forEach(r=>{const el=document.createElement('a');el.className='recent-item';el.href='#create';el.innerHTML=`<span class="doc-mini"></span><div><strong>${escapeText(get(r,'recipient')||'بدون جهة')}</strong><small>${escapeText(get(r,'eventName')||TEMPLATES[r.template]?.name||'خطاب')}</small></div><time>${escapeText(get(r,'letter_number')||'—')}</time>`;el.addEventListener('click',()=>loadIntoEditor(r));recent.appendChild(el)});const q=$('#quickTemplates');q.innerHTML='';Object.entries(TEMPLATES).forEach(([key,t])=>{const el=document.createElement('a');el.href='#create';el.className='quick-template';el.innerHTML=`<div class="template-swatch ${t.tone}"></div><strong>${t.name}</strong><small>${t.desc}</small>`;el.addEventListener('click',()=>{resetEditor(key);});q.appendChild(el)})}
function escapeText(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function currentRecord(){const r={...state};fieldIds.forEach(id=>r[id]=$(\`#${id}\`)?.value??state[id]);r.digitalStamp=$('#digitalStamp')?.checked??state.digitalStamp;return r}
function fillForm(r){fieldIds.forEach(id=>{const el=$(`#${id}`);if(el)el.value=get(r,id)});if($('#digitalStamp'))$('#digitalStamp').checked=r.digital_stamp??r.digitalStamp??true}
function selectTemplate(key){state.template=key;state.extraParam=TEMPLATES[key].extra;state.message=DEFAULT_MESSAGES[key];if($('#extraParam'))$('#extraParam').value=state.extraParam;if($('#message'))$('#message').value=state.message;$$('.editor-template').forEach(x=>x.classList.toggle('selected',x.dataset.template===key));updateLabels();updatePreview();scheduleDraft()}
function updateLabels(){const t=TEMPLATES[state.template];if($('#extraLabel'))$('#extraLabel').textContent=t.label}
function renderTemplateCards(){const root=$('#editorTemplates');root.innerHTML='';Object.entries(TEMPLATES).forEach(([key,t])=>{const el=document.createElement('button');el.type='button';el.className=`editor-template ${key===state.template?'selected':''}`;el.dataset.template=key;el.innerHTML=`<div class="template-swatch ${t.tone}"></div><strong>${t.name}</strong><small>${t.desc}</small>`;el.addEventListener('click',()=>selectTemplate(key));root.appendChild(el)})}
function initCreate(){if(!state.number)state.number=storage.nextNumber();$('#editorNumber').textContent=state.number;$('#previewNumber').textContent=state.number;renderTemplateCards();fillForm(state);updateLabels();activateTab(state.tab);updatePreview();bindCreate();fitZoom()}
function activateTab(tab){state.tab=tab;$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));$$('.form-pane').forEach(x=>x.classList.toggle('active',x.dataset.pane===tab));$('#prevTab').disabled=tab==='identity';$('#nextTab').textContent=tab==='content'?'حفظ الخطاب  ↗':'التالي  ←'}
function bindCreate(){ $$('.tab').forEach(b=>b.addEventListener('click',()=>activateTab(b.dataset.tab)));$('#prevTab').addEventListener('click',()=>activateTab(state.tab==='content'?'details':'identity'));$('#nextTab').addEventListener('click',()=>state.tab==='content'?saveDocument():activateTab(state.tab==='identity'?'details':'content'));$('#resetDraft').addEventListener('click',()=>resetEditor());$('#saveDoc').addEventListener('click',saveDocument);$('#copyText').addEventListener('click',copyDocument);$('#printDoc').addEventListener('click',printDocument);$('#zoomIn').addEventListener('click',()=>setZoom(state.zoom+.05));$('#zoomOut').addEventListener('click',()=>setZoom(state.zoom-.05));$('#fitZoom').addEventListener('click',fitZoom);fieldIds.forEach(id=>{const el=$(`#${id}`);el?.addEventListener('input',()=>{state[id]=el.value;updatePreview();scheduleDraft()})});$('#digitalStamp')?.addEventListener('change',e=>{state.digitalStamp=e.target.checked;updatePreview();scheduleDraft()});$$('[data-size]').forEach(b=>b.addEventListener('click',()=>{state.size=b.dataset.size;$$('[data-size]').forEach(x=>x.classList.toggle('active',x===b));updatePreview();fitZoom()}));}
function updatePreview(){const r=currentRecord();r.template=state.template;r.size=state.size;r.letter_number=state.number;r.digitalStamp=state.digitalStamp;$('#paper').innerHTML=paper(r);$('#paper').style.height=state.size==='square'?'794px':'1123px';$('#previewMeta').textContent=`${state.size==='a4'?'A4':'1:1'} · ${TEMPLATES[state.template].name}`;$('#previewNumber').textContent=state.number;$('#editorNumber').textContent=state.number}
function setZoom(z){state.zoom=Math.max(CONFIG.zoom.min,Math.min(CONFIG.zoom.max,z));$('#paperFrame').style.transform=`scale(${state.zoom})`;$('#zoomValue').textContent=`${Math.round(state.zoom*100)}%`;}
function fitZoom(){const stage=$('#paperStage');if(!stage)return;const w=state.size==='square'?794:794;const available=Math.max(280,stage.clientWidth-50);setZoom(Math.min(CONFIG.zoom.max,Math.max(CONFIG.zoom.min,available/w)))}
function scheduleDraft(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>{storage.saveDraft({...currentRecord(),template:state.template,size:state.size,number:state.number,id:state.id,digitalStamp:state.digitalStamp})},350)}
function saveDocument(){const r=currentRecord();r.template=state.template;r.size=state.size;r.letter_number=state.number;r.digitalStamp=state.digitalStamp;const error=validate(r);if(error){toast(error);activateTab(!r.recipient||!r.date||!r.eventName?'details':'content');return}if(!r.id)r.id=crypto.randomUUID();const owner=cloudReady?undefined:'';const record=recordFromState({...r,number:state.number,id:r.id,digitalStamp:r.digitalStamp},owner);records=storage.upsert(record);storage.clearDraft();state.id=record.id;state.number=record.letter_number;syncUI();toast('تم حفظ الخطاب بنجاح');if(cloudReady)cloudUpsert(record).then(ok=>{if(!ok)toast('تم الحفظ محليًا وتعذر المزامنة الآن')});renderHomeIfNeeded();}
function renderHomeIfNeeded(){if(state.route==='home')renderHome()}
async function copyDocument(){const r=currentRecord();try{await navigator.clipboard.writeText(plainText(r));toast('تم نسخ نص الخطاب')}catch{toast('تعذر النسخ من المتصفح')}}
function printDocument(){const r=currentRecord();const w=window.open('','_blank','noopener,noreferrer');if(!w){toast('اسمح بالنوافذ المنبثقة للطباعة');return}w.document.write(`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><title>${escapeText(state.number)}</title><style>@page{size:${state.size==='a4'?'A4':'auto'};margin:0}body{margin:0}.paper{width:794px;height:${state.size==='a4'?'1123':'794'}px}</style><link rel="stylesheet" href="${location.href.replace(/[^/]+$/,'')}style.css"></head><body><div class="paper">${paper({...r,template:state.template,letter_number:state.number,digitalStamp:state.digitalStamp})}</div><script>window.onload=()=>setTimeout(()=>window.print(),250)<\/script></body></html>`);w.document.close()}
function resetEditor(template='sponsorship'){state.id='';state.number=storage.nextNumber();state.template=template;state.size='a4';state.tab='identity';state.digitalStamp=true;fieldIds.forEach(id=>state[id]='');state.date=today();state.extraParam=TEMPLATES[template].extra;state.message=DEFAULT_MESSAGES[template];storage.clearDraft();if(location.hash!=='#create')location.hash='#create';else renderRoute()}
function loadIntoEditor(r){Object.assign(state,{id:r.id,number:get(r,'letter_number')||storage.nextNumber(),template:r.template||'sponsorship',size:r.size||'a4',digitalStamp:r.digital_stamp!==false});fieldIds.forEach(id=>state[id]=get(r,id));state.tab='identity';location.hash='#create'}
function initLibrary(){const input=$('#librarySearch');const render=()=>{const q=input.value.trim().toLowerCase();const list=records.filter(r=>[get(r,'recipient'),get(r,'eventName'),get(r,'letter_number')].some(v=>String(v).toLowerCase().includes(q)));$('#libraryCount').textContent=`${list.length} خطاب`;$('#libraryMode').textContent=cloudReady?'متزامن مع السحابة':'التخزين المحلي';const root=$('#libraryList');root.innerHTML='';if(!list.length){root.innerHTML='<div class="panel empty" style="grid-column:1/-1">لا توجد نتائج مطابقة</div>';return}list.forEach(r=>{const el=document.createElement('article');el.className='library-card';el.innerHTML=`<div class="library-thumb"></div><div class="library-card-main"><h3>${escapeText(get(r,'recipient')||'بدون جهة')}</h3><p>${escapeText(get(r,'eventName')||TEMPLATES[r.template]?.name||'خطاب')}</p><div class="meta"><span>${escapeText(get(r,'letter_number')||'—')}</span><span>${escapeText(dateText(get(r,'date')))}</span></div></div><div class="library-card-actions"><button class="small-btn edit">فتح</button><button class="small-btn danger del">حذف</button></div>`;el.querySelector('.edit').addEventListener('click',()=>loadIntoEditor(r));el.querySelector('.del').addEventListener('click',()=>deleteRecord(r));root.appendChild(el)})};input.addEventListener('input',render);$('#refreshLibrary').addEventListener('click',async()=>{await syncCloud();render();toast('تم تحديث المكتبة')});render()}
async function deleteRecord(r){if(!confirm('حذف هذا الخطاب؟'))return;records=storage.remove(r.id);syncUI();if(cloudReady)await cloudDelete(r.id);initLibrary()}
function initTemplates(){const root=$('#templateCatalog');Object.entries(TEMPLATES).forEach(([key,t])=>{const el=document.createElement('article');el.className='catalog-card';el.innerHTML=`<div class="catalog-preview ${t.tone}"></div><div><span class="tag">${t.english}</span><h2>${t.name}</h2><p>${t.desc}. تصميم مخصص للخطابات الرسمية مع معاينة مباشرة ومقاس جاهز للطباعة.</p><a class="btn primary" href="#create">استخدام القالب <b>↗</b></a></div>`;el.querySelector('a').addEventListener('click',()=>resetEditor(key));root.appendChild(el)})}
function initSettings(){const choice=localStorage.getItem(CONFIG.themeKey)||'system';$$('[data-theme-choice]').forEach(b=>{b.classList.toggle('active',b.dataset.themeChoice===choice);b.addEventListener('click',()=>{applyTheme(b.dataset.themeChoice);toast('تم تحديث المظهر')})});$('#recordsSetting').textContent=records.length;$('#cloudSettingStatus').textContent=cloudReady?'متزامن':'محلي';$('#clearLocal').addEventListener('click',()=>{if(!confirm('سيتم حذف جميع الخطابات المحلية والمسودة. هل تريد المتابعة؟'))return;storage.clear();records=[];syncUI();initSettings();toast('تم مسح البيانات المحلية')})}
async function syncCloud(){const list=await cloudList();if(!Array.isArray(list))return;const map=new Map(records.map(r=>[r.id,r]));for(const r of list){const local=map.get(r.id);if(!local||new Date(r.updated_at)>new Date(local.updated_at))map.set(r.id,r)}records=[...map.values()].sort((a,b)=>new Date(b.updated_at)-new Date(a.updated_at));storage.set(records);storage.syncSequence(records);cloudReady=true;syncUI()}
async function boot(){records=storage.migrate();storage.syncSequence(records);applyTheme();syncUI();const draft=storage.draft();if(draft&&!state.id){Object.assign(state,draft);state.number=state.number||storage.nextNumber();}const ok=await cloudStatus();if(ok){cloudReady=true;await syncCloud()}else cloudReady=false;syncUI();const mq=matchMedia('(prefers-color-scheme:light)');mq.addEventListener?.('change',()=>{if((localStorage.getItem(CONFIG.themeKey)||'system')==='system')applyTheme('system')});renderRoute()}
$('#themeBtn').addEventListener('click',()=>{const current=localStorage.getItem(CONFIG.themeKey)||'system';applyTheme(current==='dark'?'light':current==='light'?'system':'dark')});$('#menuBtn').addEventListener('click',()=>{$('#sidebar').classList.add('open');$('#backdrop').classList.add('show')});$('#backdrop').addEventListener('click',closeMobile);function closeMobile(){$('#sidebar').classList.remove('open');$('#backdrop').classList.remove('show')};$('#newButton')?.addEventListener('click',()=>resetEditor());document.addEventListener('click',e=>{const a=e.target.closest('a[data-route],a[href^="#"]');if(a&&a.getAttribute('href')?.startsWith('#')){const route=a.dataset.route||a.getAttribute('href').slice(1);if(ROUTES[route]){e.preventDefault();setRoute(route)}}});window.addEventListener('hashchange',()=>{const r=location.hash.slice(1)||'home';if(r==='create'&&state.id){ }state.route=ROUTES[r]?r:'home';renderRoute()});window.addEventListener('resize',()=>{if(state.route==='create')fitZoom()});document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='n'&&!/input|textarea/i.test(e.target.tagName)){e.preventDefault();resetEditor()}});boot();
