import {CONFIG} from './config.js';
let session=null;
let authPromise=null;
const headers=()=>({apikey:CONFIG.supabase.key,Authorization:`Bearer ${session?.access_token||CONFIG.supabase.key}`,'Content-Type':'application/json'});
async function req(path,options={}){const res=await fetch(CONFIG.supabase.url+path,{...options,headers:{...headers(),...(options.headers||{})}});if(!res.ok){const err=new Error(`HTTP ${res.status}`);err.status=res.status;throw err}return res.status===204?null:res.json()}
export async function connect(){if(session?.access_token)return session;if(authPromise)return authPromise;authPromise=(async()=>{const data=await req('/auth/v1/signup',{method:'POST',body:'{}'});if(!data?.access_token||!data?.user?.id)throw new Error('AUTH_FAILED');session=data;return session})().finally(()=>{authPromise=null});return authPromise}
export async function cloudUpsert(record){const s=await connect();const payload={id:record.id,owner_id:s.user.id,is_anonymous:true,letter_number:record.number,template:record.template,size:record.size,recipient:record.recipient,recipient_name:record.recipientName||null,event_name:record.eventName,date:record.date,extra_param:record.extraParam||null,value:record.value||null,message:record.message,pr_name:record.prName||null,pr_contact:record.prContact||null,pr_email:record.prEmail||null,digital_stamp:!!record.digitalStamp,created_at:record.createdAt,updated_at:record.updatedAt};return req(`/rest/v1/${CONFIG.supabase.table}?on_conflict=id`,{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(payload)})}
export async function cloudList(){await connect();return req(`/rest/v1/${CONFIG.supabase.table}?select=*&order=updated_at.desc`)}
export async function cloudDelete(id){await connect();return req(`/rest/v1/${CONFIG.supabase.table}?id=eq.${encodeURIComponent(id)}`,{method:'DELETE',headers:{Prefer:'return=minimal'}})}
