import {CONFIG} from './data.js';
let session=null, authPromise=null;
const endpoint=(path)=>`${CONFIG.supabase.url}${path}`;
async function request(url,options={}){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),CONFIG.requestTimeout);try{const res=await fetch(url,{...options,signal:controller.signal});const text=await res.text();let body=null;try{body=text?JSON.parse(text):null}catch{}if(!res.ok){const e=new Error(body?.message||body?.error_description||'Cloud request failed');e.status=res.status;throw e}return body}finally{clearTimeout(timer)}}
async function auth(){if(authPromise)return authPromise;authPromise=(async()=>{try{const saved=JSON.parse(localStorage.getItem('paic_studio_auth')||'null');if(saved?.access_token){try{const user=await request(endpoint('/auth/v1/user'),{headers:{apikey:CONFIG.supabase.key,Authorization:`Bearer ${saved.access_token}`}});session={...saved,user};return session}catch{if(saved.refresh_token){try{const refreshed=await request(endpoint('/auth/v1/token?grant_type=refresh_token'),{method:'POST',headers:{apikey:CONFIG.supabase.key,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:saved.refresh_token})});if(refreshed?.access_token){localStorage.setItem('paic_studio_auth',JSON.stringify(refreshed));session=refreshed;return session}}catch{}}}}
const created=await request(endpoint('/auth/v1/signup'),{method:'POST',headers:{apikey:CONFIG.supabase.key,'Content-Type':'application/json'},body:'{}'});if(!created?.access_token||!created?.user?.id)throw new Error('Anonymous auth unavailable');localStorage.setItem('paic_studio_auth',JSON.stringify(created));session=created;return session}catch{return null}finally{authPromise=null}})();return authPromise}
export async function cloudStatus(){const s=await auth();return !!s?.access_token}
export async function cloudList(){const s=await auth();if(!s)return null;try{return await request(endpoint(`/rest/v1/${CONFIG.supabase.table}?select=*&order=updated_at.desc`),{headers:{apikey:CONFIG.supabase.key,Authorization:`Bearer ${s.access_token}`}})}catch{return null}}
export async function cloudUpsert(record){const s=await auth();if(!s)return false;const payload={...record,owner_id:s.user?.id||record.owner_id};try{await request(endpoint(`/rest/v1/${CONFIG.supabase.table}?on_conflict=id`),{method:'POST',headers:{apikey:CONFIG.supabase.key,Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(payload)});return true}catch{return false}}
export async function cloudDelete(id){const s=await auth();if(!s)return false;try{await request(endpoint(`/rest/v1/${CONFIG.supabase.table}?id=eq.${encodeURIComponent(id)}`),{method:'DELETE',headers:{apikey:CONFIG.supabase.key,Authorization:`Bearer ${s.access_token}`}});return true}catch{return false}}
