import {CONFIG} from './config.js';
import {store} from './store.js';
let session=store.session();
let authPromise=null;
const base=CONFIG.supabase.url;
const headers=()=>({apikey:CONFIG.supabase.key,Authorization:`Bearer ${session?.access_token||CONFIG.supabase.key}`,'Content-Type':'application/json'});
async function request(path,options={},retry=true){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),CONFIG.timeouts.request);try{const res=await fetch(base+path,{...options,signal:controller.signal,headers:{...headers(),...(options.headers||{})}});if(res.status===401&&retry){session=null;store.clearSession();await connect();return request(path,options,false)}if(!res.ok){const err=new Error(`HTTP_${res.status}`);err.status=res.status;throw err}return res.status===204?null:res.json()}finally{clearTimeout(timer)}}
export async function connect(){if(session?.access_token&&session?.user?.id)return session;if(authPromise)return authPromise;authPromise=(async()=>{const saved=store.session();if(saved?.access_token&&saved?.user?.id){session=saved;return session}const res=await fetch(`${base}/auth/v1/signup`,{method:'POST',headers:{apikey:CONFIG.supabase.key,'Content-Type':'application/json'},body:'{}'});if(!res.ok)throw new Error('AUTH_FAILED');const data=await res.json();if(!data?.access_token||!data?.user?.id)throw new Error('AUTH_FAILED');session=data;store.saveSession(data);return data})().finally(()=>authPromise=null);return authPromise}
const payload=(r,userId)=>({id:r.id,owner_id:userId,is_anonymous:true,letter_number:r.number,template:r.template,size:r.size,recipient:r.recipient,recipient_name:r.recipientName||null,event_name:r.eventName,date:r.date,extra_param:r.extraParam||null,value:r.value||null,message:r.message,pr_name:r.prName||null,pr_contact:r.prContact||null,pr_email:r.prEmail||null,digital_stamp:!!r.digitalStamp,created_at:r.createdAt,updated_at:r.updatedAt});
export async function cloudUpsert(r){const s=await connect();return request(`/rest/v1/${CONFIG.supabase.table}?on_conflict=id`,{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(payload(r,s.user.id))})}
export async function cloudList(){await connect();return request(`/rest/v1/${CONFIG.supabase.table}?select=*&order=updated_at.desc`)}
export async function cloudDelete(id){await connect();return request(`/rest/v1/${CONFIG.supabase.table}?id=eq.${encodeURIComponent(id)}`,{method:'DELETE',headers:{Prefer:'return=minimal'}})}
