import {TEMPLATES} from './templates.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
export const blank=()=>({id:'',number:'',template:'classic',size:'a4',recipient:'',recipientName:'',eventName:'',date:new Date().toISOString().slice(0,10),extraParam:'',value:'',message:'',prName:'',prContact:'',prEmail:'',digitalStamp:true,createdAt:'',updatedAt:''});
export const defaults=v=>({...blank(),...v});
export const formatDate=r=>{if(!r)return '—';const d=new Date(`${r}T00:00:00`);if(Number.isNaN(d.getTime()))return r;return new Intl.DateTimeFormat('ar-SA-u-ca-gregory',{day:'numeric',month:'long',year:'numeric'}).format(d)};
export const validate=r=>{const e=[];if(!r.recipient.trim())e.push('الجهة');if(!r.eventName.trim())e.push('الموضوع');if(!r.date)e.push('التاريخ');if(!r.message.trim())e.push('نص الخطاب');if(r.prEmail&&!/^\S+@\S+\.\S+$/.test(r.prEmail))e.push('البريد الإلكتروني');return e};
export const plainText=r=>[`جامعة الطائف — كلية الحاسبات وتقنية المعلومات`,`نادي البرمجة والذكاء الاصطناعي`,`رقم الخطاب: ${r.number||'—'}`,`التاريخ: ${formatDate(r.date)}`,`الجهة: ${r.recipient||'—'}`,r.recipientName&&`عناية: ${r.recipientName}`,`الموضوع: ${r.eventName||'—'}`,'',r.message,r.extraParam&&`نوع الخطاب: ${r.extraParam}`,r.value&&`القيمة / الدعم: ${r.value}`,'',r.prName&&`مسؤول العلاقات العامة: ${r.prName}`,r.prContact&&`التواصل: ${r.prContact}`,r.prEmail&&`البريد: ${r.prEmail}`].filter(Boolean).join('\n');
export function paper(r){
 const t=TEMPLATES[r.template]||TEMPLATES.classic;const square=r.size==='square';const message=(r.message||'').trim()||'اكتب نص الخطاب من المحرر وسيظهر هنا مباشرة.';const lines=esc(message).replace(/\n/g,'<br>');
 return `<article class="paper paper-${r.template} ${square?'paper-square':''}" style="--accent:${t.accent}">
 <div class="paper-topline"></div><div class="paper-corner corner-a"></div><div class="paper-corner corner-b"></div>
 <header class="paper-head"><div class="uni"><img src="assets/logo-university.svg"><div>جامعة الطائف<small>كلية الحاسبات وتقنية المعلومات</small></div></div><div class="club"><img src="assets/logo-club.svg"><div>نادي البرمجة والذكاء الاصطناعي<small>PROGRAMMING & AI CLUB</small></div></div></header>
 <div class="paper-meta"><span><small>رقم الخطاب</small><b>${esc(r.number||'PAIC-0001')}</b></span><span><small>التاريخ</small><b>${esc(formatDate(r.date))}</b></span></div>
 <main class="paper-body"><div class="recipient">السادة / <b>${esc(r.recipient||'الجهة المستهدفة')}</b>${r.recipientName?`<small>عناية / ${esc(r.recipientName)}</small>`:''}</div><div class="greeting">السلام عليكم ورحمة الله وبركاته، وبعد،</div><div class="subject"><small>الموضوع</small><h1>${esc(r.eventName||'عنوان الخطاب الرسمي')}</h1></div><div class="message">${lines}</div>${(r.extraParam||r.value)?`<div class="paper-info">${r.extraParam?`<span><small>نوع الخطاب</small><b>${esc(r.extraParam)}</b></span>`:''}${r.value?`<span><small>القيمة / الدعم</small><b>${esc(r.value)}</b></span>`:''}</div>`:''}<div class="closing">وتفضلوا بقبول خالص التحية والتقدير.</div></main>
 <footer class="paper-foot"><div class="signature"><span class="stamp ${r.digitalStamp?'':'off'}">PAIC<small>OFFICIAL</small></span><div><b>${esc(r.prName||'مسؤول العلاقات العامة')}</b><small>${esc(r.prContact||'')} ${r.prEmail?` · ${esc(r.prEmail)}`:''}</small></div></div><div class="paper-id">نادي البرمجة والذكاء الاصطناعي<br><small>جامعة الطائف · كلية الحاسبات وتقنية المعلومات</small></div></footer>
 </article>`;
}
