import {paperSvg} from './document.js';
function safeName(name){return String(name||'PAIC-Letter').trim().replace(/[\\/:*?"<>|]+/g,'-').replace(/\s+/g,' ').slice(0,90)||'PAIC-Letter'}
function svgBlob(svg){return new Blob([`<?xml version="1.0" encoding="UTF-8"?>${svg}`],{type:'image/svg+xml;charset=utf-8'})}
async function svgImage(r){const svg=paperSvg(r);const blob=svgBlob(svg);const url=URL.createObjectURL(blob);try{const img=new Image();img.decoding='async';await new Promise((res,rej)=>{img.onload=res;img.onerror=rej;img.src=url});return {img,w:r.size==='square'?794:794,h:r.size==='square'?794:1123}}finally{URL.revokeObjectURL(url)}}
async function canvasFor(r,scale=2){const {img,w,h}=await svgImage(r);const c=document.createElement('canvas');c.width=w*scale;c.height=h*scale;const ctx=c.getContext('2d',{alpha:false});ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(img,0,0,c.width,c.height);return c}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000)}
export async function downloadPng(r){const c=await canvasFor(r,2);const blob=await new Promise(res=>c.toBlob(res,'image/png'));if(!blob)throw new Error('PNG failed');download(blob,`${safeName(r.recipient||r.eventName||r.number)}.png`)}
function escBytes(s){return new TextEncoder().encode(s)}
function concat(parts){let n=0;for(const p of parts)n+=p.length;const o=new Uint8Array(n);let at=0;for(const p of parts){o.set(p,at);at+=p.length}return o}
export async function downloadPdf(r){const c=await canvasFor(r,2);const jpeg=await new Promise(res=>c.toBlob(res,'image/jpeg',.92));if(!jpeg)throw new Error('PDF image failed');const imgBytes=new Uint8Array(await jpeg.arrayBuffer());const W=c.width,H=c.height;const objs=[];const add=x=>{objs.push(typeof x==='string'?escBytes(x):x);return objs.length};const catalog=add('');const pages=add('');const page=add('');const image=add('');const content=add('');
const imgHead=escBytes(`<< /Type /XObject /Subtype /Image /Width ${W} /Height ${H} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${imgBytes.length} >>\nstream\n`);const imgObj=concat([imgHead,imgBytes,escBytes('\nendstream')]);objs[image-1]=imgObj;const contentBytes=escBytes(`q\n595 0 0 842 0 0 cm\n/Im1 Do\nQ`);objs[content-1]=escBytes(`<< /Length ${contentBytes.length} >>\nstream\n${new TextDecoder().decode(contentBytes)}\nendstream`);objs[page-1]=escBytes(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /XObject << /Im1 4 0 R >> >> /Contents 5 0 R >>`);objs[pages-1]=escBytes(`<< /Type /Pages /Kids [3 0 R] /Count 1 >>`);objs[catalog-1]=escBytes(`<< /Type /Catalog /Pages 2 0 R >>`);
let out=[escBytes('%PDF-1.4\n%âãÏÓ\n')];const offsets=[0];let pos=out[0].length;for(let i=0;i<objs.length;i++){offsets.push(pos);const head=escBytes(`${i+1} 0 obj\n`);const tail=escBytes('\nendobj\n');out.push(head,objs[i],tail);pos+=head.length+objs[i].length+tail.length}const xref=pos;let x=`xref\n0 ${objs.length+1}\n0000000000 65535 f \n`;for(let i=1;i<offsets.length;i++)x+=String(offsets[i]).padStart(10,'0')+' 00000 n \n';x+=`trailer\n<< /Size ${objs.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;out.push(escBytes(x));download(new Blob([concat(out)],{type:'application/pdf'}),`${safeName(r.recipient||r.eventName||r.number)}.pdf`)}
