import {CONFIG} from './config.js'; import {store} from './store.js'; import {TEMPLATES,templateCards} from './templates.js'; import {blank,defaults,numberFor,paper,text,validate} from './document.js';
const app=document.querySelector('#app'),toast=document.querySelector('#toast');
const state={page:'home',editor:defaults(store.draft()||{}),step:1,query:'',theme:store.theme(),cloud:'محلي'};
const nav=[['home','الرئيسية'],['create','إنشاء خطاب'],['library','المحفوظات'],['templates','القوالب']];
const icon={home:'⌂',create:'＋',library:'▤',templates:'◇',settings:'⚙'};
function notify(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(notify.t);notify.t=setTimeout(()=>toast.classList.remove('show'),2400)}
function applyTheme(){const t=state.theme==='system'?(matchMedia('(prefers-color-scheme:light)').matches?'light':'dark'):state.theme;document.documentElement.dataset.theme=t}
function shell(content){app.innerHTML=`<aside class="sidebar"><div class="side-brand"><span><img src="assets/logo-club.svg"></span><div><b>PAIC</b><small>STUDIO</small></div></div><nav>${nav.map(([id,label])=>`<a href="#/${id}" class="${state.page===id?'active':''}"><i>${icon[id]}</i>${label}</a>`).join('')}</nav><div class="side-bottom"><a href="#/settings" class="${state.page==='settings'?'active':''}"><i>⚙</i>الإعدادات</a><div class="side-note"><small>PAIC DOCUMENT STUDIO</small><strong>خطابات مرتبة<br>في مكان واحد</strong></div></div></aside><div class="main"><header class="topbar"><button class="mobile-menu" data-action="menu">☰</button><div><span class="crumb">PAIC STUDIO / ${nav.find(x=>x[0]===state.page)?.[1]||'الإعدادات'}</span><h1>${nav.find(x=>x[0]===state.page)?.[1]||'الإعدادات'}</h1></div><div class="top-actions"><span class="cloud-pill"><i></i>${state.cloud}</span><button class="theme" data-action="theme">◐</button><a class="primary" href="#/create">+ خطاب جديد</a></div></header><main class="content">${content}</main></div>`;}
function home(){const records=store.records();return `<section class="welcome"><div><span class="badge">PAIC · DOCUMENT STUDIO</span><h2>كل خطاب يبدأ<br><em>بشكل مرتب.</em></h2><p>أنشئ خطابات النادي الرسمية من مكان واحد، اختر القالب وعدّل المحتوى وشاهد النتيجة مباشرة.</p><div class="actions"><a class="primary big" href="#/create">إنشاء خطاب جديد ↗</a><a class="ghost big" href="#/library">فتح المحفوظات</a></div></div><div class="hero-art"><div class="art-glow"></div><div class="mini-card"><small>PAIC / LETTER</small><b>جاهز للإرسال</b><span>${new Date().getFullYear()} · رسمي</span></div><div class="mini-paper"><i></i><i></i><i class="short"></i><b>PAIC</b></div></div></section><section class="dashboard-grid"><div class="panel intro"><div class="panel-head"><div><small>WORKFLOW</small><h3>أنشئ الخطاب بثلاث خطوات</h3></div></div><div class="workflow"><div><b>01</b><strong>اختر القالب</strong><span>هوية مناسبة لنوع الخطاب</span></div><div><b>02</b><strong>اكتب البيانات</strong><span>المعلومات والمحتوى</span></div><div><b>03</b><strong>راجع وصدّر</strong><span>طباعة أو PDF</span></div></div></div><div class="panel stat-panel"><small>المحفوظات</small><strong>${records.length}</strong><span>خطاب محفوظ</span><a href="#/library">عرض الكل →</a></div><div class="panel stat-panel"><small>القوالب</small><strong>04</strong><span>هويات جاهزة</span><a href="#/templates">استعراض →</a></div></section><section class="panel recent"><div class="panel-head"><div><small>RECENT</small><h3>آخر الخطابات</h3></div><a href="#/library">كل المحفوظات →</a></div>${records.slice(0,4).map(recordCard).join('')||`<div class="empty"><strong>لا توجد خطابات بعد</strong><span>ابدأ بإنشاء أول خطاب لك</span><a class="primary" href="#/create">إنشاء خطاب</a></div>`}</section>`}
function recordCard(r){return `<article class="record"><div class="record-mark" style="--accent:${TEMPLATES[r.template]?.accent||'#8b5cf6'}">${(r.number||'PAIC').slice(-3)}</div><div class="record-info"><strong>${escapeHtml(r.eventName||'خطاب بدون عنوان')}</strong><span>${escapeHtml(r.recipient||'—')} · ${escapeHtml(r.number||'—')}</span></div><span class="record-template">${TEMPLATES[r.template]?.name||'قالب'}</span><button data-open="${r.id}">فتح ↗</button></article>`}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function create(){return `<section class="editor-layout"><div class="editor-main panel"><div class="editor-head"><div><span class="badge">NEW LETTER</span><h2>${state.editor.number||'خطاب جديد'}</h2></div><div class="editor-tools"><button data-action="reset">مسودة جديدة</button><span id="editorStatus">محفوظ محليًا</span></div></div><div class="steps">${[['1','الهوية'],['2','البيانات'],['3','المحتوى']].map(([n,l])=>`<button class="${state.step==n?'active':''}" data-step="${n}"><b>${n}</b><span>${l}</span></button>`).join('')}</div><div class="editor-body">${state.step===1?stepOne():state.step===2?stepTwo():stepThree()}</div><div class="editor-foot"><button class="ghost" data-action="prev" ${state.step===1?'disabled':''}>السابق</button><button class="primary" data-action="next">${state.step===3?'حفظ الخطاب':'التالي'} ${state.step===3?'✓':'←'}</button></div></div><aside class="preview panel"><div class="preview-head"><div><small>LIVE PREVIEW</small><strong>${state.editor.size==='a4'?'A4':'1:1'} · ${TEMPLATES[state.editor.template].name}</strong></div><div class="zoom"><button data-action="zoomOut">−</button><span id="zoomLabel">70%</span><button data-action="zoomIn">+</button></div></div><div class="paper-wrap" id="paperWrap"><div id="paperFrame">${paper(state.editor)}</div></div><div class="preview-foot"><button class="ghost" data-action="copy">نسخ النص</button><button class="ghost" data-action="print">طباعة</button><button class="primary" data-action="save">حفظ الخطاب</button></div></aside></section>`}
function stepOne(){return `<div class="pane-title"><span>01</span><div><h3>اختر هوية الخطاب</h3><p>كل قالب مصمم لاستخدام مختلف مع نفس الهوية الرسمية.</p></div></div><div class="templates">${templateCards(state.editor.template)}</div><div class="size-choice"><div><strong>مقاس المستند</strong><small>A4 للطباعة الرسمية أو مربع للتصاميم المختصرة</small></div><div>${['a4','square'].map(x=>`<button class="${state.editor.size===x?'active':''}" data-size="${x}">${x==='a4'?'A4':'1:1'}</button>`).join('')}</div></div>`}
function input(id,label,wide=false,type='text'){return `<label class="field ${wide?'wide':''}"><span>${label}</span><input data-field="${id}" type="${type}" value="${escapeHtml(state.editor[id]||'')}" maxlength="500"></label>`}
function stepTwo(){return `<div class="pane-title"><span>02</span><div><h3>بيانات الخطاب</h3><p>المعلومات التي تظهر في الورقة الرسمية.</p></div></div><div class="fields">${input('recipient','الجهة *')}${input('recipientName','اسم المسؤول')}${input('date','التاريخ *',false,'date')}${input('eventName','الفعالية / المبادرة *',true)}${input('extraParam','نوع / شكل الرعاية',true)}${input('value','القيمة')}</div>`}
function stepThree(){return `<div class="pane-title"><span>03</span><div><h3>المحتوى والتواصل</h3><p>اكتب النص النهائي وبيانات مسؤول العلاقات العامة.</p></div></div><label class="field wide"><span>نص الخطاب *</span><textarea data-field="message" maxlength="12000">${escapeHtml(state.editor.message||'')}</textarea></label><div class="fields compact">${input('prName','مسؤول العلاقات العامة')}${input('prContact','رقم التواصل')}${input('prEmail','البريد الإلكتروني',true,'email')}</div><label class="check"><input data-field="digitalStamp" type="checkbox" ${state.editor.digitalStamp?'checked':''}><span></span><b>ختم PAIC الرقمي</b></label>`}
function library(){let rs=store.records();if(state.query)rs=rs.filter(r=>`${r.recipient} ${r.eventName} ${r.number}`.toLowerCase().includes(state.query.toLowerCase()));return `<section class="library-page"><div class="page-tools"><div><span class="badge">LETTER LIBRARY</span><h2>المحفوظات</h2><p>كل الخطابات التي أنشأتها محفوظة هنا.</p></div><div class="search"><input id="search" value="${escapeHtml(state.query)}" placeholder="ابحث عن جهة أو رقم أو فعالية"><a class="primary" href="#/create">+ جديد</a></div></div><div class="library-list">${rs.map(recordCard).join('')||`<div class="empty"><strong>لا توجد نتائج</strong><span>جرّب كلمة بحث مختلفة أو أنشئ خطابًا جديدًا</span></div>`}</div></section>`}
function templates(){return `<section class="templates-page"><div class="page-tools"><div><span class="badge">TEMPLATE GALLERY</span><h2>القوالب</h2><p>اختر الهوية قبل البدء وشاهد الفرق بين التصاميم.</p></div></div><div class="gallery">${Object.entries(TEMPLATES).map(([id,t],i)=>`<article><div class="gallery-paper" style="--accent:${t.accent}"><b>PAIC</b><i></i><i></i><i class="short"></i><span>${String(i+1).padStart(2,'0')}</span></div><div><small>0${i+1} / TEMPLATE</small><h3>${t.name}</h3><p>${t.desc}</p><a href="#/create?template=${id}">استخدم القالب →</a></div></article>`).join('')}</div></section>`}
function settings(){return `<section class="settings-page"><div class="page-tools"><div><span class="badge">PREFERENCES</span><h2>الإعدادات</h2><p>تحكم في مظهر المنصة وطريقة عملها.</p></div></div><div class="settings-grid"><article class="panel setting"><small>APPEARANCE</small><h3>المظهر</h3><p>اختر الوضع المناسب أو اجعل الموقع يتبع جهازك.</p><div class="theme-options">${['system','dark','light'].map(x=>`<button class="${state.theme===x?'active':''}" data-theme="${x}">${x==='system'?'النظام':x==='dark'?'داكن':'فاتح'}</button>`).join('')}</div></article><article class="panel setting"><small>STORAGE</small><h3>الحفظ</h3><p>المحفوظات المحلية تعمل حتى عند تعذر الاتصال بالسحابة.</p><div class="storage-line"><span>خطابات محلية</span><b>${store.records().length}</b></div></article></div></section>`}
function render(){applyTheme();const content=state.page==='home'?home():state.page==='create'?create():state.page==='library'?library():state.page==='templates'?templates():settings();shell(content);}
function persistDraft(){store.saveDraft(state.editor)}
function save(){const errors=validate(state.editor);if(errors.length){notify(`أكمل: ${errors.join('، ')}`);return false}const now=new Date().toISOString();let r={...state.editor,id:state.editor.id||crypto.randomUUID(),number:state.editor.number||numberFor(store.records()),createdAt:state.editor.createdAt||now,updatedAt:now};const all=store.records().filter(x=>x.id!==r.id);store.saveRecords([r,...all].sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt)));state.editor=r;store.clearDraft();state.cloud='محلي';notify('تم حفظ الخطاب بنجاح');render();return true}
app.addEventListener('input',e=>{const f=e.target.dataset.field;if(!f)return;state.editor[f]=e.target.type==='checkbox'?e.target.checked:e.target.value;persistDraft();const p=document.querySelector('#paperFrame');if(p)p.innerHTML=paper(state.editor)});
app.addEventListener('click',e=>{const a=e.target.closest('a');if(a?.hash){const u=new URL(a.href);const page=u.hash.slice(2).split('?')[0];if(page){state.page=page;if(page==='create'){const q=u.hash.split('?')[1];const id=new URLSearchParams(q).get('template');if(id)state.editor=defaults({...blank(),template:id});}render();return}}const b=e.target.closest('button');if(!b)return;if(b.dataset.template){state.editor.template=b.dataset.template;persistDraft();render();return}if(b.dataset.size){state.editor.size=b.dataset.size;persistDraft();render();return}if(b.dataset.step){state.step=Number(b.dataset.step);render();return}if(b.dataset.open){const r=store.records().find(x=>x.id===b.dataset.open);if(r){state.editor=defaults(r);state.step=1;state.page='create';persistDraft();render()}return}const ac=b.dataset.action;if(ac==='theme'){state.theme=state.theme==='dark'?'light':'dark';store.setTheme(state.theme);applyTheme();return}if(ac==='reset'){state.editor=defaults({...blank(),number:numberFor(store.records())});state.step=1;store.clearDraft();render();return}if(ac==='next'){if(state.step<3){state.step++;render()}else save();return}if(ac==='prev'){state.step=Math.max(1,state.step-1);render();return}if(ac==='save'){save();return}if(ac==='copy'){navigator.clipboard?.writeText(text(state.editor));notify('تم نسخ نص الخطاب');return}if(ac==='print'){window.print();return}if(ac==='zoomIn'||ac==='zoomOut'){const frame=document.querySelector('#paperFrame');let z=Number(frame.dataset.zoom||.7)+(ac==='zoomIn'?.05:-.05);z=Math.max(.4,Math.min(1.1,z));frame.dataset.zoom=z;frame.style.transform=`scale(${z})`;document.querySelector('#zoomLabel').textContent=Math.round(z*100)+'%';return}if(b.dataset.theme){state.theme=b.dataset.theme;store.setTheme(state.theme);render()}});
document.addEventListener('input',e=>{if(e.target.id==='search'){state.query=e.target.value;render();requestAnimationFrame(()=>{const s=document.querySelector('#search');s?.focus();s?.setSelectionRange(s.value.length,s.value.length)})}});
window.addEventListener('hashchange',()=>{const p=location.hash.slice(2).split('?')[0]||'home';state.page=p;render()});
if(!location.hash)history.replaceState(null,'','#/home');state.page=location.hash.slice(2).split('?')[0]||'home';render();
