(()=>{'use strict';
const CONFIG={url:'https://ddwekucnbmzktbzaoxmj.supabase.co',key:'sb_publishable_bPLVqBXOMQc0DZj3UIz2tg_o0KR8llE',table:'paic_letters_v9'};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const fields=['recipient','recipientName','date','eventName','extraParam','value','message','prName','prContact','prEmail'];
const LS={draft:'paic_v9_draft',records:'paic_v9_records',session:'paic_v9_session',theme:'paic_v9_theme',seq:'paic_v9_seq'};
const state={template:'sponsorship',size:'a4',number:'',zoom:.68,stamp:true,session:null,userId:null,saving:false};
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Riyadh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function fmt(v){if(!v)return '—';try{return new Intl.DateTimeFormat('ar-SA',{dateStyle:'long',timeZone:'Asia/Riyadh'}).format(new Date(v+'T12:00:00'))}catch{return v}}
function nextNumber(){const y=new Intl.DateTimeFormat('en',{timeZone:'Asia/Riyadh',year:'numeric'}).format(new Date());const k=`${LS.seq}_${y}`;const n=Number(localStorage.getItem(k)||0)+1;localStorage.setItem(k,n);return `PAIC-${y}-${String(n).padStart(4,'0')}`}
function data(){const d={};fields.forEach(id=>d[id]=$('#'+id)?.value||'');return {...d,template:state.template,size:state.size,number:state.number,stamp:state.stamp}}
function defaultMessage(){const t=PAIC_CONTENT.templates[state.template];if(state.template==='sponsorship')return `السلام عليكم ورحمة الله وبركاته،\n\nسعادة مسؤولي {{recipient}} المحترمين،\nتحية طيبة وبعد،\n\nيسرّنا في نادي البرمجة والذكاء الاصطناعي بجامعة الطائف – كلية الحاسبات وتقنية المعلومات أن نتقدم إليكم بطلب رعاية لـ {{eventName}}، والمقرر إقامتها بتاريخ {{date}}، وذلك انطلاقًا من حرصنا على تقديم أنشطة نوعية تسهم في تمكين طلاب وطالبات الجامعة، وإثراء تجربتهم التعليمية والتقنية، ودعم بيئة الابتكار والمشاركة الطلابية.\n\nونأمل منكم التكرم بالمساهمة في دعم الفعالية من خلال {{extraParam}}{{valuePart}}، وذلك بما يتناسب مع طبيعة الفعالية واحتياجاتها.\n\nونؤمن بأن الشراكة معكم تمثل فرصة لتحقيق منفعة متبادلة، حيث نحرص بدورنا على تقدير مساهمتكم وإبراز دعمكم للأنشطة والمبادرات الطلابية، وذلك من خلال توجيه الشكر للجهة الراعية والإشارة إليها عبر حسابات النادي الرسمية، وفق ما يتناسب مع طبيعة الرعاية والفعالية.\n\nشاكرين ومقدّرين لكم وقتكم واهتمامكم، ومتطلعين إلى بناء تعاون مثمر وبنّاء.\n\nوتفضلوا بقبول فائق الاحترام والتقدير.`;
return `السلام عليكم ورحمة الله وبركاته،\n\nسعادة {{recipientName}} المحترم،\nتحية طيبة وبعد،\n\nيسرّ نادي البرمجة والذكاء الاصطناعي بجامعة الطائف أن يتقدم إليكم بخطاب ${t.name} بشأن {{eventName}} والمقرر إقامتها بتاريخ {{date}}.\n\n{{extraParam}}\n\n${t.closing}`}
function replaceTokens(text){const d=data();return text.replaceAll('{{recipient}}',d.recipient||'اسم الجهة').replaceAll('{{recipientName}}',d.recipientName||d.recipient||'المكرم').replaceAll('{{eventName}}',d.eventName||'اسم الفعالية أو المبادرة').replaceAll('{{date}}',fmt(d.date)).replaceAll('{{extraParam}}',d.extraParam||PAIC_CONTENT.templates[state.template].extraDefault).replaceAll('{{valuePart}}',d.value?`، بما يقدّر بـ ${d.value}`:'')}
function paras(text){return text.split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean).map(x=>`<p>${esc(replaceTokens(x)).replace(/\n/g,'<br>')}</p>`).join('')}
function logos(){return `<div class="logos"><img class="uni-logo" src="${PAIC_CONTENT.brand.universityLogo}" alt="جامعة الطائف"><div class="club-lock"><img src="${PAIC_CONTENT.brand.clubLogo}" alt="PAIC"><span>${esc(PAIC_CONTENT.brand.club)}</span></div></div>`}
function contact(d){return `<div class="contact"><div><b>قسم العلاقات العامة</b><span>${esc(d.prName||'—')}</span></div><div><b>رقم التواصل</b><span>${esc(d.prContact||'—')}</span></div><div><b>البريد الإلكتروني</b><span>${esc(d.prEmail||'—')}</span></div><div><b>الجهة</b><span>${esc(d.recipient||'—')}</span></div></div>`}
function stamp(){return state.stamp?`<div class="stamp"><b>PAIC</b><small>DIGITAL REFERENCE</small><small>${esc(state.number)}</small></div>`:''}
function render(){const t=PAIC_CONTENT.templates[state.template],d=data(),p=$('#paper');p.className=`paper ${state.template}${state.size==='square'?' square':''}`;p.style.setProperty('--accent',t.accent);$('#previewMeta').textContent=`${state.size==='a4'?'A4':'مربع'} · ${t.name}`;const head=`<div class="doc-top"><span>${esc(t.eyebrow)}</span><strong>${esc(state.number)}</strong></div>`;const title=`<h2 class="title">${esc(t.title)}</h2><div class="subtitle">${esc(t.subtitle)}</div>`;const recipient=`<div class="recipient">سعادة ${esc(d.recipientName||d.recipient||'المكرم')} المحترم،</div>`;const body=`<div class="body">${paras(d.message||defaultMessage())}</div>`;const meta=`<div class="meta-row"><span>${esc(fmt(d.date))}</span><span>${esc(d.eventName||'اسم الفعالية')}</span></div>`;let extra=`<div class="highlight"><b>${esc(t.extraLabel)}</b><span>${esc(d.extraParam||t.extraDefault)}</span>${d.value?`<small>القيمة المقترحة: ${esc(d.value)}</small>`:''}</div>`;
let inner='';
if(state.template==='invitation')inner=`<div class="paper-inner">${logos()}${head}${title}${recipient}${meta}${body}${extra}<div class="signature">مع خالص التحية والتقدير<br><b>نادي البرمجة والذكاء الاصطناعي</b></div>${stamp()}</div>`;
else if(state.template==='thanks')inner=`<div class="paper-inner">${logos()}${head}${title}${recipient}${body}${extra}${contact(d)}<div class="footer"><span>جامعة الطائف · كلية الحاسبات وتقنية المعلومات</span><span>${esc(state.number)}</span></div>${stamp()}</div>`;
else inner=`<div class="paper-inner">${logos()}${head}${title}${recipient}${meta}${body}${extra}${contact(d)}<div class="footer"><span>جامعة الطائف · كلية الحاسبات وتقنية المعلومات</span><span>${esc(state.number)}</span></div>${stamp()}</div>`;
p.innerHTML=inner;scale();draft()}
function scale(){const f=$('#paperFrame'),p=$('#paper'),s=state.zoom,w=793.7,h=state.size==='a4'?1122.5:793.7;f.style.width=w*s+'px';f.style.height=h*s+'px';p.style.transform=`scale(${s})`;$('#zoomValue').textContent=Math.round(s*100)+'%'}
function fit(){const st=$('#paperStage');const w=Math.max(240,st.clientWidth-60),h=Math.max(300,st.clientHeight-60),pw=793.7,ph=state.size==='a4'?1122.5:793.7;state.zoom=Math.max(.35,Math.min(1.05,w/pw,h/ph));scale()}
function selectTemplate(){const t=PAIC_CONTENT.templates[state.template];$$('.template-card').forEach(x=>x.classList.toggle('active',x.dataset.template===state.template));$('#extraLabel').textContent=t.extraLabel;$('#extraParam').placeholder=t.extraDefault}
function selectSize(){ $$('.segmented button').forEach(x=>x.classList.toggle('active',x.dataset.size===state.size));scale() }
function draft(){clearTimeout(state.draftTimer);state.draftTimer=setTimeout(()=>localStorage.setItem(LS.draft,JSON.stringify(data())),120)}
function localRecords(){try{return JSON.parse(localStorage.getItem(LS.records)||'[]')}catch{return[]}}
function setState(text,ok=true){$('#saveStateText').textContent=text;$('.live-dot').style.background=ok?'#4c8b73':'#b17a36'}
async function request(path,opts={},auth=true){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),6500);try{const h={apikey:CONFIG.key,Accept:'application/json','Content-Type':'application/json',...opts.headers};if(auth&&state.session?.access_token)h.Authorization=`Bearer ${state.session.access_token}`;const r=await fetch(`${CONFIG.url}${path}`,{...opts,headers:h,signal:controller.signal});const txt=await r.text();let body=null;try{body=txt?JSON.parse(txt):null}catch{}if(!r.ok)throw new Error(body?.message||body?.msg||`HTTP ${r.status}`);return body}finally{clearTimeout(timer)}}
async function authInit(){const saved=JSON.parse(localStorage.getItem(LS.session)||'null');if(saved?.access_token){try{const u=await request('/auth/v1/user');state.session=saved;state.userId=u.id;setState('السحابة متصلة');return}catch{localStorage.removeItem(LS.session)}}try{const s=await request('/auth/v1/signup',{method:'POST',body:'{}'},false);if(s?.access_token&&s?.user?.id){state.session={access_token:s.access_token,refresh_token:s.refresh_token,user:s.user};state.userId=s.user.id;localStorage.setItem(LS.session,JSON.stringify(state.session));setState('السحابة متصلة');return}}catch{}setState('محلي فقط',false)}
function payload(){const d=data();return {owner_id:state.userId,id:d.number,letter_number:d.number,template:d.template,size:d.size,recipient:d.recipient,recipient_name:d.recipientName,date:d.date,event_name:d.eventName,extra_param:d.extraParam,message:d.message,pr_name:d.prName,pr_contact:d.prContact,pr_email:d.prEmail,stamp_enabled:d.stamp,updated_at:new Date().toISOString()}}
async function save(){const d=data();if(!d.recipient||!d.eventName||!d.message){toast('أكمل الحقول المطلوبة أولًا');return}const rec={...d,savedAt:new Date().toISOString()};localStorage.setItem(LS.records,JSON.stringify([rec,...localRecords().filter(x=>x.number!==d.number)].slice(0,100)));setState('جار الحفظ…');if(!state.userId){setState('محفوظ محليًا',false);toast('حُفظ محليًا — فعّل Anonymous Sign-ins في Supabase');renderRecords();return}try{await request(`/rest/v1/${CONFIG.table}?on_conflict=owner_id,letter_number`,{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(payload())});setState('محفوظ سحابيًا');toast('تم حفظ الخطاب');renderRecords()}catch(e){setState('محفوظ محليًا',false);toast('تم الحفظ محليًا — تعذر مزامنة السحابة');renderRecords()}}
async function sync(){if(!state.userId)return;try{const rows=await request(`/rest/v1/${CONFIG.table}?owner_id=eq.${encodeURIComponent(state.userId)}&order=updated_at.desc&limit=100`);const local=localRecords();const cloud=(rows||[]).map(r=>({number:r.letter_number,template:r.template,size:r.size,recipient:r.recipient,recipientName:r.recipient_name,date:r.date,eventName:r.event_name,extraParam:r.extra_param,value:'',message:r.message,prName:r.pr_name,prContact:r.pr_contact,prEmail:r.pr_email,stamp:r.stamp_enabled,savedAt:r.updated_at}));const map=new Map([...local,...cloud].map(x=>[x.number,x]));localStorage.setItem(LS.records,JSON.stringify([...map.values()].sort((a,b)=>String(b.savedAt).localeCompare(String(a.savedAt))).slice(0,100)));renderRecords()}catch{}}
function renderRecords(){const q=($('#librarySearch').value||'').toLowerCase().trim(),rows=localRecords().filter(x=>`${x.recipient} ${x.number} ${x.eventName}`.toLowerCase().includes(q));$('#recordsList').innerHTML=rows.length?rows.map(x=>`<div class="record"><div class="record-main"><b>${esc(x.recipient||'بدون جهة')}</b><small>${esc(x.number)} · ${esc(x.eventName||'')}</small></div><div class="record-actions"><button data-open="${esc(x.number)}">فتح</button><button data-copy="${esc(x.number)}">نسخ</button><button data-delete="${esc(x.number)}">حذف</button></div></div>`).join(''):'<div class="empty">لا توجد خطابات محفوظة بعد</div>'}
function openLibrary(){renderRecords();$('#libraryModal').classList.add('open');$('#libraryModal').setAttribute('aria-hidden','false');setTimeout(()=>$('#librarySearch').focus(),30)}function closeLibrary(){$('#libraryModal').classList.remove('open');$('#libraryModal').setAttribute('aria-hidden','true')}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2200)}
function fill(d){fields.forEach(id=>{if($('#'+id))$('#'+id).value=d[id]??''});state.template=d.template||'sponsorship';state.size=d.size||'a4';state.number=d.number||nextNumber();state.stamp=d.stamp!==false;$('#digitalStamp').checked=state.stamp;selectTemplate();selectSize();render()}
function newLetter(){if(!confirm('بدء خطاب جديد؟'))return;fields.forEach(id=>$('#'+id).value='');state.template='sponsorship';state.size='a4';state.number=nextNumber();state.stamp=true;$('#digitalStamp').checked=true;$('#date').value=today();$('#extraParam').value=PAIC_CONTENT.templates.sponsorship.extraDefault;$('#message').value=defaultMessage();selectTemplate();selectSize();render();toast('تم إنشاء خطاب جديد')}
async function del(n){const row=localRecords().find(x=>x.number===n);localStorage.setItem(LS.records,JSON.stringify(localRecords().filter(x=>x.number!==n)));renderRecords();if(state.userId){try{await request(`/rest/v1/${CONFIG.table}?owner_id=eq.${encodeURIComponent(state.userId)}&letter_number=eq.${encodeURIComponent(n)}`,{method:'DELETE'})}catch{}}toast('تم حذف الخطاب')}
async function copy(){try{await navigator.clipboard.writeText(replaceTokens($('#message').value||''));toast('تم نسخ النص')}catch{toast('تعذر النسخ من المتصفح')}}
function pdf(){const win=window.open('','_blank');if(!win){toast('اسمح بالنوافذ المنبثقة لإخراج PDF');return}const clone=$('#paper').cloneNode(true);clone.style.transform='none';const href=new URL('style.css',location.href).href;win.document.write(`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><link rel="stylesheet" href="${href}"><style>@page{size:${state.size==='a4'?'A4':'210mm 210mm'};margin:0}body{margin:0;background:#fff}.paper{box-shadow:none!important;transform:none!important}</style></head><body></body></html>`);win.document.close();win.onload=()=>{win.document.body.appendChild(clone);setTimeout(()=>win.print(),250)}}
function bind(){
$('#templateGrid').innerHTML=Object.entries(PAIC_CONTENT.templates).map(([k,t])=>`<button class="template-card" data-template="${k}" style="--card-accent:${t.accent}"><span class="mini">${t.icon}</span><b>${t.name}</b><small>${t.eyebrow}</small></button>`).join('');selectTemplate();
$('#templateGrid').addEventListener('click',e=>{const b=e.target.closest('[data-template]');if(!b)return;const changed=state.template!==b.dataset.template;state.template=b.dataset.template;const t=PAIC_CONTENT.templates[state.template];$('#extraParam').value=t.extraDefault;if(changed)$('#message').value=defaultMessage();selectTemplate();render()});
$$('.segmented button').forEach(b=>b.addEventListener('click',()=>{state.size=b.dataset.size;selectSize();render()}));
fields.forEach(id=>$('#'+id).addEventListener('input',render));$('#digitalStamp').addEventListener('change',()=>{state.stamp=$('#digitalStamp').checked;render()});
$('#saveBtn').addEventListener('click',save);$('#newBtn').addEventListener('click',newLetter);$('#libraryBtn').addEventListener('click',openLibrary);$$('[data-close]').forEach(b=>b.addEventListener('click',closeLibrary));$('#libraryModal').addEventListener('click',e=>{if(e.target.id==='libraryModal')closeLibrary()});$('#librarySearch').addEventListener('input',renderRecords);
$('#recordsList').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const n=b.dataset.open||b.dataset.copy||b.dataset.delete;const r=localRecords().find(x=>x.number===n);if(b.dataset.open&&r){fill(r);closeLibrary();toast('تم فتح الخطاب')}else if(b.dataset.copy&&r){navigator.clipboard?.writeText(replaceTokens(r.message||''));toast('تم النسخ')}else if(b.dataset.delete&&r&&confirm('حذف الخطاب المحفوظ؟'))del(n)});
$('#zoomIn').addEventListener('click',()=>{state.zoom=Math.min(1.2,state.zoom+.06);scale()});$('#zoomOut').addEventListener('click',()=>{state.zoom=Math.max(.35,state.zoom-.06);scale()});$('#fitBtn').addEventListener('click',fit);$('#copyBtn').addEventListener('click',copy);$('#printBtn').addEventListener('click',()=>window.print());$('#pdfBtn').addEventListener('click',pdf);
$('#themeBtn').addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem(LS.theme,document.body.classList.contains('dark')?'dark':'light')});
$$('.mobile-switch button').forEach(b=>b.addEventListener('click',()=>{document.body.classList.toggle('mobile-preview',b.dataset.view==='preview');$$('.mobile-switch button').forEach(x=>x.classList.toggle('active',x===b));if(b.dataset.view==='preview')setTimeout(fit,80)}));
$('#brandHome').addEventListener('click',e=>{e.preventDefault();window.scrollTo({top:0,behavior:'smooth'})});document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='s'){e.preventDefault();save()}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openLibrary()}if(e.key==='Escape')closeLibrary()});
}
function init(){if(localStorage.getItem(LS.theme)==='dark')document.body.classList.add('dark');bind();const saved=JSON.parse(localStorage.getItem(LS.draft)||'null');if(saved)fill(saved);else{state.number=nextNumber();$('#date').value=today();$('#extraParam').value=PAIC_CONTENT.templates.sponsorship.extraDefault;$('#message').value=defaultMessage();render()}fit();authInit().then(sync)}init();
})();
