const SUPA={url:'https://ddwekucnbmzktbzaoxmj.supabase.co',key:'sb_publishable_bPLVqBXOMQc0DZj3UIz2tg_o0KR8llE',table:'paic_letters_v13'};
const C=window.PAIC_CONTENT;const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const KEY='paic_v13';
const state={template:'sponsorship',size:'a4',step:1,zoom:.7,id:null,number:null,cloud:'local',records:[],saving:false};
const fields=['recipient','recipientName','date','eventName','extraParam','value','message','prName','prContact','prEmail'];
let SESSION=null;
const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
const dateRiyadh=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Riyadh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const getJSON=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const val=id=>$('#'+id)?.value||''; const set=(id,v)=>{if($('#'+id))$('#'+id).value=v??''};
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.remove('show'),2400)}
function nextNumber(){const k=KEY+'_seq';let n=Number(localStorage.getItem(k)||0)+1;localStorage.setItem(k,String(n));return `PAIC-${new Date().getFullYear()}-${String(n).padStart(4,'0')}`}
function fillDefaults(){if(!val('date'))set('date',dateRiyadh());const t=C.templates[state.template];if(!val('message'))set('message',state.template==='sponsorship'?C.sponsorshipText:C.defaults[state.template]);if(!val('extraParam'))set('extraParam',t.defaultExtra);$('#extraLabel').textContent=t.label}
function renderTemplates(){const icons={sponsorship:'R',partnership:'P',invitation:'I',thanks:'T'};$('#templateGrid').innerHTML=Object.entries(C.templates).map(([k,t])=>`<button type="button" class="template ${k===state.template?'active':''}" data-template="${k}"><i class="template-mark ${k}">${icons[k]}</i><span><b>${esc(t.name)}</b><small>${esc(t.desc)}</small></span><strong>↗</strong></button>`).join('');$$('.template').forEach(b=>b.onclick=()=>{state.template=b.dataset.template;set('message','');set('extraParam','');fillDefaults();renderTemplates();renderPaper();saveDraft()})}
function resolveText(s){return String(s||'').replaceAll('[اسم الجهة]',val('recipient')||'اسم الجهة').replaceAll('[اسم المسؤول]',val('recipientName')||'المسؤول المختص').replaceAll('[التاريخ]',val('date')||'التاريخ').replaceAll('[اسم الفعالية/المبادرة]',val('eventName')||'الفعالية / المبادرة').replaceAll('[نوع/شكل الرعاية أو المساهمة]',val('extraParam')||'نوع الرعاية أو المساهمة').replaceAll('[نوع/شكل الرعاية]',val('extraParam')||'نوع الرعاية').replaceAll('[مجال الشراكة]',val('extraParam')||'مجال الشراكة').replaceAll('[طبيعة المشاركة]',val('extraParam')||'طبيعة المشاركة').replaceAll('[سبب التكريم]',val('extraParam')||'سبب التكريم').replaceAll('[القيمة إن وجدت]',val('value')||'القيمة').replaceAll('[القيمة]',val('value')||'القيمة')}
function paperBody(){const t=C.templates[state.template],stamp=$('#digitalStamp')?.checked!==false;const message=resolveText(val('message')).split(/\n\s*\n+/).filter(Boolean).map(x=>`<p>${esc(x).replaceAll('\n','<br>')}</p>`).join('');const event=esc(val('eventName')||'اسم الفعالية / المبادرة');const rec=esc(val('recipient')||'اسم الجهة');const name=esc(val('recipientName'));const d=esc(val('date')||dateRiyadh());const n=esc(state.number||'—');const extra=esc(val('extraParam')||t.defaultExtra);const value=esc(val('value'));return `<div class="doc ${t.tone}"><div class="doc-shape s1"></div><div class="doc-shape s2"></div><div class="doc-topline"><span>جامعة الطائف</span><span>كلية الحاسبات وتقنية المعلومات</span><span>PAIC</span></div><header class="doc-head"><img src="assets/logo-university.svg" alt="جامعة الطائف"><div class="doc-id"><small>PAIC · DOCUMENT</small><b>${n}</b><span>${d}</span></div><img src="assets/logo-club.svg" alt="نادي البرمجة والذكاء الاصطناعي"></header><div class="accent"></div><div class="doc-meta"><span>إلى</span><strong>${rec}</strong>${name?`<em>${name}</em>`:''}</div><div class="doc-title"><small>${t.english}</small><h1>${esc(t.name)}</h1><b>${event}</b></div><div class="doc-content">${message}</div><div class="detail-row"><div><small>${esc(t.label)}</small><b>${extra}</b></div>${value?`<div><small>القيمة</small><b>${value}</b></div>`:''}</div><footer class="doc-foot"><div><b>${esc(val('prName')||'قسم العلاقات العامة')}</b><span>${esc(val('prContact'))}</span><span>${esc(val('prEmail'))}</span></div>${stamp?`<div class="stamp"><span>PAIC</span><b>${n}</b><small>DIGITAL</small></div>`:''}</footer></div>`}
function renderPaper(){if(!state.number)state.number=nextNumber();const p=$('#paper');p.className=`paper size-${state.size}`;p.innerHTML=paperBody();$('#previewMeta').textContent=`${state.size==='a4'?'A4':'مربع'} · ${C.templates[state.template].name}`;fit()}
function fit(){const stage=$('#paperStage');if(!stage)return;const baseW=794,baseH=state.size==='a4'?1123:794;const pad=window.innerWidth<=650?18:46;const availableW=Math.max(220,stage.clientWidth-pad);const availableH=Math.max(260,stage.clientHeight-pad);state.zoom=Math.min(availableW/baseW,availableH/baseH,1);if(!Number.isFinite(state.zoom)||state.zoom<=0)state.zoom=.5;applyZoom()}
function applyZoom(){const p=$('#paper'),frame=$('#paperFrame');if(!p||!frame)return;const baseH=state.size==='a4'?1123:794;state.zoom=Math.max(.35,Math.min(1.25,state.zoom));p.style.transform=`scale(${state.zoom})`;frame.style.width=(794*state.zoom)+'px';frame.style.height=(baseH*state.zoom)+'px';$('#zoomValue').textContent=Math.round(state.zoom*100)+'%'}
function setStep(n){state.step=Math.max(1,Math.min(3,n));$$('.step').forEach(x=>x.classList.toggle('active',+x.dataset.step===state.step));$$('.pane').forEach(x=>x.classList.toggle('active',+x.dataset.pane===state.step));$('#prevStep').hidden=state.step===1;$('#nextStep').innerHTML=state.step===3?'حفظ <span>↗</span>':'التالي <span>←</span>'}
function ownerId(){return SESSION?.user?.id||''}
function payload(){return {id:state.id||crypto.randomUUID(),owner_id:ownerId(),letter_number:state.number,template:state.template,size:state.size,recipient:val('recipient').trim(),recipient_name:val('recipientName').trim(),date:val('date'),event_name:val('eventName').trim(),extra_param:val('extraParam').trim(),value:val('value').trim(),message:val('message').trim(),pr_name:val('prName').trim(),pr_contact:val('prContact').trim(),pr_email:val('prEmail').trim(),digital_stamp:$('#digitalStamp')?.checked!==false}}
function saveDraft(){const o=payload();localStorage.setItem(KEY+'_draft',JSON.stringify(o))}
function localSave(o){const a=getJSON(KEY+'_records',[]);const i=a.findIndex(x=>x.id===o.id);if(i>=0)a[i]={...a[i],...o};else a.unshift(o);localStorage.setItem(KEY+'_records',JSON.stringify(a));state.records=a;renderRecords()}
function setCloud(text,kind='ok'){$('#saveState').innerHTML=`<i class="${kind}"></i>${text}`}
function loadStoredSession(){return getJSON(KEY+'_session',null)}
function storeSession(s){if(s?.access_token&&s?.refresh_token){localStorage.setItem(KEY+'_session',JSON.stringify({access_token:s.access_token,refresh_token:s.refresh_token,user:s.user}));SESSION=s}}
async function request(url,opts={},timeout=7000){const ctrl=new AbortController();const timer=setTimeout(()=>ctrl.abort(),timeout);try{return await fetch(url,{...opts,signal:ctrl.signal})}finally{clearTimeout(timer)}}
async function auth(){if(SESSION?.access_token)return SESSION;const stored=loadStoredSession();if(stored?.access_token){SESSION=stored;try{const r=await request(`${SUPA.url.replace('/rest/v1','')}/auth/v1/user`,{headers:{apikey:SUPA.key,Authorization:`Bearer ${SESSION.access_token}`}});if(r.ok){SESSION.user=await r.json();return SESSION}}catch{}if(stored.refresh_token){try{const r=await request(`${SUPA.url.replace('/rest/v1','')}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:SUPA.key,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:stored.refresh_token})});if(r.ok){storeSession(await r.json());return SESSION}}catch{}}localStorage.removeItem(KEY+'_session');SESSION=null}
const r=await request(`${SUPA.url.replace('/rest/v1','')}/auth/v1/signup`,{method:'POST',headers:{apikey:SUPA.key,'Content-Type':'application/json'},body:'{}'});if(!r.ok)throw new Error(await r.text());const s=await r.json();storeSession(s);return SESSION}
async function cloud(path='',opts={}){await auth();if(!SESSION?.access_token)throw new Error('No session');const headers={apikey:SUPA.key,Authorization:`Bearer ${SESSION.access_token}`,'Content-Type':'application/json',Prefer:'return=representation,resolution=merge-duplicates',...(opts.headers||{})};const r=await request(`${SUPA.url}/${SUPA.table}${path}`,{...opts,headers});if(r.status===401){localStorage.removeItem(KEY+'_session');SESSION=null;await auth();return cloud(path,opts)}if(!r.ok)throw new Error(await r.text());const text=await r.text();return text?JSON.parse(text):[]}
async function save(){if(state.saving)return;const o=payload();if(!o.recipient||!o.date||!o.event_name||!o.message){toast('أكمل الجهة والتاريخ والفعالية ونص الخطاب');setStep(!o.message?3:2);return}if(o.pr_email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(o.pr_email)){toast('تحقق من البريد الإلكتروني');setStep(3);return}if(o.message.length>12000){toast('نص الخطاب طويل جدًا');setStep(3);return}state.saving=true;localSave(o);state.id=o.id;setCloud('جاري الحفظ','busy');try{await cloud('?on_conflict=id',{method:'POST',body:JSON.stringify(o)});state.cloud='cloud';setCloud('متزامن مع السحابة','ok');toast('تم حفظ الخطاب بنجاح');localStorage.removeItem(KEY+'_draft')}catch(e){state.cloud='local';setCloud('محفوظ محليًا','warn');toast('حُفظ محليًا — تعذر الوصول للسحابة الآن')}finally{state.saving=false}}
function renderRecords(){const q=val('librarySearch').trim().toLowerCase();const a=state.records.filter(x=>`${x.recipient} ${x.letter_number} ${x.event_name}`.toLowerCase().includes(q));$('#recordsList').innerHTML=a.length?a.map(x=>`<article class="record"><div><b>${esc(x.recipient||'بدون جهة')}</b><small>${esc(x.letter_number||'')} · ${esc(x.event_name||'')}</small></div><div class="record-actions"><button class="outline" data-open="${esc(x.id)}">فتح</button><button class="outline danger" data-delete="${esc(x.id)}">حذف</button></div></article>`).join(''):`<div class="empty"><b>${q?'لا توجد نتائج':'لا توجد خطابات محفوظة'}</b><small>${q?'جرّب كلمة بحث أخرى':'ابدأ بإنشاء خطابك الأول'}</small></div>`;$$('[data-open]').forEach(b=>b.onclick=()=>openRecord(b.dataset.open));$$('[data-delete]').forEach(b=>b.onclick=()=>deleteRecord(b.dataset.delete))}
function openRecord(id){const x=state.records.find(r=>r.id===id);if(!x)return;state.id=x.id;state.number=x.letter_number;state.template=x.template;state.size=x.size;fields.forEach(k=>set(k,x[k]||''));if($('#digitalStamp'))$('#digitalStamp').checked=x.digital_stamp!==false;renderTemplates();renderPaper();location.hash='create';setStep(2);window.scrollTo({top:document.querySelector('#create').offsetTop-90,behavior:'smooth'});toast('تم فتح الخطاب')}
async function deleteRecord(id){state.records=state.records.filter(x=>x.id!==id);localStorage.setItem(KEY+'_records',JSON.stringify(state.records));renderRecords();try{await cloud('/'+encodeURIComponent(id),{method:'DELETE'})}catch{}toast('تم حذف الخطاب')}
function newLetter(){state.id=null;state.number=nextNumber();fields.forEach(k=>set(k,''));set('prName','قسم العلاقات العامة');if($('#digitalStamp'))$('#digitalStamp').checked=true;fillDefaults();setStep(1);renderPaper();saveDraft();location.hash='create';window.scrollTo({top:document.querySelector('#create').offsetTop-90,behavior:'smooth'})}
async function loadCloud(){try{await auth();const a=await cloud('?select=*&order=updated_at.desc');const local=getJSON(KEY+'_records',[]);const map=new Map([...local,...a].map(x=>[x.id,x]));state.records=[...map.values()].sort((x,y)=>new Date(y.updated_at||0)-new Date(x.updated_at||0));localStorage.setItem(KEY+'_records',JSON.stringify(state.records));state.cloud='cloud';setCloud('السحابة متصلة','ok');renderRecords()}catch(e){state.records=getJSON(KEY+'_records',[]);state.cloud='local';setCloud('محلي','warn');renderRecords()}}
function restoreDraft(){const d=getJSON(KEY+'_draft',null);if(!d)return false;if(!d.id||!d.letter_number)return false;state.id=d.id;state.number=d.letter_number;state.template=d.template||state.template;state.size=d.size||'a4';fields.forEach(k=>set(k,d[k]||''));if($('#digitalStamp'))$('#digitalStamp').checked=d.digital_stamp!==false;return true}
function bind(){if(localStorage.getItem(KEY+'_theme')==='light')document.body.classList.add('light');const restored=restoreDraft();renderTemplates();fillDefaults();renderPaper();setStep(1);fields.forEach(id=>$('#'+id)?.addEventListener('input',()=>{renderPaper();saveDraft()}));$('#digitalStamp')?.addEventListener('change',()=>{renderPaper();saveDraft()});$$('[data-size]').forEach(b=>b.onclick=()=>{state.size=b.dataset.size;$$('[data-size]').forEach(x=>x.classList.toggle('active',x===b));renderPaper();saveDraft()});$$('.step').forEach(b=>b.onclick=()=>setStep(+b.dataset.step));$('#nextStep').onclick=()=>state.step===3?save():setStep(state.step+1);$('#prevStep').onclick=()=>setStep(state.step-1);$('#saveBtn').onclick=save;$('#newBtn').onclick=newLetter;$('#heroCreate').onclick=newLetter;$('#heroLibrary').onclick=()=>{location.hash='library';window.scrollTo({top:$('#library').offsetTop-80,behavior:'smooth'})};$('#copyBtn').onclick=async()=>{try{await navigator.clipboard.writeText(resolveText(val('message')));toast('تم نسخ النص')}catch{toast('تعذر النسخ من المتصفح')}};$('#printBtn').onclick=printDocument;$('#pdfBtn').onclick=printDocument;function printDocument(){const style=document.createElement('style');style.id='paic-print-size';style.textContent=`@page{size:${state.size==='a4'?'A4':'210mm 210mm'};margin:0}`;document.head.appendChild(style);window.addEventListener('afterprint',()=>style.remove(),{once:true});window.print();setTimeout(()=>style.remove(),5000)}$('#zoomIn').onclick=()=>{state.zoom+=.05;applyZoom()};$('#zoomOut').onclick=()=>{state.zoom-=.05;applyZoom()};$('#fitBtn').onclick=fit;$('#librarySearch').oninput=renderRecords;$('#refreshBtn').onclick=loadCloud;$('#themeBtn').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem(KEY+'_theme',document.body.classList.contains('light')?'light':'dark')};window.addEventListener('resize',()=>fit());if(!restored)saveDraft();loadCloud();}
document.addEventListener('DOMContentLoaded',bind);
