(() => {
'use strict';
const CONFIG={supabaseUrl:'https://ddwekucnbmzktbzaoxmj.supabase.co',publishableKey:'sb_publishable_bPLVqBXOMQc0DZj3UIz2tg_o0KR8llE',table:'paic_letters_v8'};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fields=['recipient','recipientName','date','eventName','extraParam','value','message','prName','prContact','prEmail'];
const state={template:'sponsorship',size:'a4',number:'',zoom:0.72,stamp:true,records:[],saveTimer:null};
const STORAGE='paic_studio_v8_draft', RECORDS='paic_studio_v8_records', CLIENT='paic_studio_v8_client', THEME='paic_studio_v8_theme';
const uid=()=>{let x=localStorage.getItem(CLIENT);if(!x){x=(crypto.randomUUID?crypto.randomUUID():'c-'+Date.now()+'-'+Math.random().toString(16).slice(2));localStorage.setItem(CLIENT,x)}return x};
const clientId=uid();
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Riyadh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function formatDate(v){if(!v)return '—';try{return new Intl.DateTimeFormat('ar-SA',{dateStyle:'long',timeZone:'Asia/Riyadh'}).format(new Date(v+'T12:00:00'))}catch{return v}}
function number(){let y=new Date().toLocaleString('en-US',{timeZone:'Asia/Riyadh',year:'numeric'});let key='paic_seq_'+y,n=+(localStorage.getItem(key)||0)+1;localStorage.setItem(key,String(n));return `PAIC-${y}-${String(n).padStart(4,'0')}`}
function data(){const o={};fields.forEach(id=>o[id]=$('#'+id)?.value||'');o.template=state.template;o.size=state.size;o.number=state.number;o.stamp=state.stamp;return o}
function fill(d){fields.forEach(id=>{if($('#'+id)&&d[id]!==undefined)$('#'+id).value=d[id]});state.template=d.template||state.template;state.size=d.size||'a4';state.number=d.number||state.number||number();state.stamp=d.stamp!==false;$('#digitalStamp').checked=state.stamp;selectTemplate();selectSize();updateExtra();render()}
function defaultMessage(){const t=PAIC_CONTENT.templates[state.template];let s=t.intro.replaceAll('{{recipient}}','{{recipient}}').replaceAll('{{eventName}}','{{eventName}}').replaceAll('{{date}}','{{date}}');let r=t.request;return `${s}\n\n${r}\n\n${t.closing}`}
function seed(){const d=JSON.parse(localStorage.getItem(STORAGE)||'null');if(d){fill(d);return}$('#date').value=today();state.number=number();updateExtra();$('#message').value=defaultMessage();render()}
function replaceTokens(text){const d=data();let s=text.replaceAll('{{recipient}}',d.recipient||'اسم الجهة').replaceAll('{{recipientName}}',d.recipientName||'').replaceAll('{{eventName}}',d.eventName||'اسم الفعالية').replaceAll('{{date}}',formatDate(d.date)).replaceAll('{{extraParam}}',d.extraParam||'التفاصيل').replaceAll('{{valuePart}}',d.value?`، بما يقدّر بـ ${d.value}`:'');return s}
function paragraphs(text){return text.split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean).map(x=>`<p>${esc(replaceTokens(x)).replace(/\n/g,'<br>')}</p>`).join('')}
function render(){const t=PAIC_CONTENT.templates[state.template],d=data(),p=$('#paper');p.className=`paper ${state.template}${state.size==='square'?' square':''}`;$('#previewMeta').textContent=`${state.size==='a4'?'A4':'مربع'} · ${t.name}`;const value=d.value?`، بما يقدّر بـ ${d.value}`:'';
const commonContact=`<div class="contact"><div><strong>قسم العلاقات العامة</strong>${esc(d.prName||'اسم المسؤول')}</div><div><strong>رقم التواصل</strong>${esc(d.prContact||'رقم التواصل')}</div><div><strong>البريد الإلكتروني</strong>${esc(d.prEmail||'البريد الإلكتروني')}</div><div><strong>الجهة</strong>${esc(d.recipient||'اسم الجهة')}</div></div>`;
let body='';
if(state.template==='sponsorship')body=`<div class="hero-band"></div><div class="paper-inner"><div class="logos"><img src="assets/logo-university.svg" alt="جامعة الطائف"><div class="club-lock"><img src="assets/logo-club.svg" alt="PAIC"><span>نادي البرمجة والذكاء الاصطناعي</span></div></div><div class="meta-row"><span>التاريخ: ${esc(formatDate(d.date))}</span><span class="doc-no">رقم الخطاب: ${esc(state.number)}</span></div><h2 class="title">${esc(t.title)}</h2><div class="recipient">سعادة مسؤولي ${esc(d.recipient||'اسم الجهة')} المحترمين،</div><div class="body">${paragraphs(d.message||defaultMessage())}<div class="highlight"><b>${esc(t.extraLabel)}</b><span>${esc(d.extraParam||t.extraDefault)}</span>${d.value?`<small style="display:block;margin-top:5px;color:#527267">القيمة المقترحة: ${esc(d.value)}</small>`:''}</div></div>${commonContact}<div class="footer"><span>نادي البرمجة والذكاء الاصطناعي · جامعة الطائف</span><span>${esc(state.number)}</span></div>${state.stamp?stampHtml('emerald'):''}</div>`;
else if(state.template==='partnership')body=`<div class="inner-mark"></div><div class="paper-inner"><div class="logos"><div class="club-lock"><img src="assets/logo-club.svg" alt="PAIC"><span>PAIC · Programming & AI Club</span></div><img src="assets/logo-university.svg" alt="جامعة الطائف"></div><div class="meta-row"><span>${esc(formatDate(d.date))}</span><span class="doc-no">${esc(state.number)}</span></div><h2 class="title">${esc(t.title)}</h2><div class="recipient">سعادة مسؤولي ${esc(d.recipient||'اسم الجهة')} المحترمين،</div><div class="body">${paragraphs(d.message||defaultMessage())}<div class="highlight"><b>${esc(t.extraLabel)}</b><span>${esc(d.extraParam||t.extraDefault)}</span></div></div>${commonContact}<div class="footer"><span>كلية الحاسبات وتقنية المعلومات</span><span>PAIC</span></div>${state.stamp?stampHtml('violet'):''}</div>`;
else if(state.template==='invitation')body=`<div class="inner-mark"></div><div class="paper-inner"><div class="logos"><img src="assets/logo-university.svg" alt="جامعة الطائف"></div><div class="meta-row"><span>${esc(formatDate(d.date))}</span><span class="doc-no">${esc(state.number)}</span></div><h2 class="title">${esc(t.title)}</h2><div class="recipient">سعادة ${esc(d.recipientName||d.recipient||'الضيف الكريم')} المحترم</div><div class="body">${paragraphs(d.message||defaultMessage())}<div class="highlight"><b>تفاصيل المشاركة</b><span>${esc(d.extraParam||t.extraDefault)}</span></div></div>${commonContact}<div class="footer"><span>يسرنا تشريفكم</span><span>PAIC</span></div>${state.stamp?stampHtml('gold'):''}</div>`;
else body=`<div class="paper-inner"><div class="logos"><img src="assets/logo-university.svg" alt="جامعة الطائف"><div class="club-lock"><img src="assets/logo-club.svg" alt="PAIC"><span>نادي البرمجة والذكاء الاصطناعي</span></div></div><div class="meta-row"><span>${esc(formatDate(d.date))}</span><span class="doc-no">${esc(state.number)}</span></div><h2 class="title">${esc(t.title)}</h2><div class="recipient">سعادة ${esc(d.recipientName||d.recipient||'المكرم')} المحترم</div><div class="body">${paragraphs(d.message||defaultMessage())}<div class="highlight"><b>${esc(t.extraLabel)}</b><span>${esc(d.extraParam||t.extraDefault)}</span></div></div>${commonContact}<div class="footer"><span>مع خالص التقدير</span><span>PAIC</span></div>${state.stamp?stampHtml('blue'):''}</div>`;
p.innerHTML=body;applyPaperScale();saveDraft();}
function stampHtml(c){return `<div class="stamp" style="color:var(--stamp-${c},#397198)"><div><b>PAIC</b><small>DIGITAL IDENTITY</small><small>${esc(state.number)}</small></div></div>`}
function applyPaperScale(){const p=$('#paper'),f=$('#paperFrame');const w=210*3.779527559,h=(state.size==='a4'?297:210)*3.779527559;const s=state.zoom;f.style.width=`${w*s}px`;f.style.height=`${h*s}px`;p.style.transform=`scale(${s})`;p.style.transformOrigin='top right';$('#zoomValue').textContent=Math.round(s*100)+'%'}
function selectTemplate(){ $$('.template-card').forEach(x=>x.classList.toggle('active',x.dataset.template===state.template));const t=PAIC_CONTENT.templates[state.template];$('#extraLabel').textContent=t.extraLabel;$('#extraParam').placeholder=t.extraDefault}
function updateExtra(){const t=PAIC_CONTENT.templates[state.template];if(!$('#extraParam').value)$('#extraParam').value=t.extraDefault}
function selectSize(){$$('.size-switch button').forEach(x=>x.classList.toggle('active',x.dataset.size===state.size));applyPaperScale()}
function toast(m){const e=$('#toast');e.textContent=m;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2200)}
function saveDraft(){clearTimeout(state.saveTimer);state.saveTimer=setTimeout(()=>localStorage.setItem(STORAGE,JSON.stringify(data())),150)}
function localRecords(){try{return JSON.parse(localStorage.getItem(RECORDS)||'[]')}catch{return[]}}
function setSaveState(text,ok=true){$('#saveState span').textContent=text;$('#saveState i').style.background=ok?'#25a87d':'#d59b38'}
async function cloud(path='',opts={}){const c=new AbortController();const timer=setTimeout(()=>c.abort(),7000);try{const r=await fetch(`${CONFIG.supabaseUrl}/rest/v1/${CONFIG.table}${path}`,{...opts,signal:c.signal,headers:{apikey:CONFIG.publishableKey,Authorization:`Bearer ${CONFIG.publishableKey}`,Accept:'application/json','Content-Type':'application/json',Prefer:'return=representation', 'x-paic-client':clientId,...(opts.headers||{})}});if(!r.ok)throw new Error(`Supabase ${r.status}`);return await r.json()}finally{clearTimeout(timer)}}
function payload(){const d=data();return {id:d.number,client_id:clientId,letter_number:d.number,template:d.template,size:d.size,recipient:d.recipient,recipient_name:d.recipientName,date:d.date,event_name:d.eventName,extra_param:d.extraParam,message:d.message,pr_name:d.prName,pr_contact:d.prContact,pr_email:d.prEmail,stamp_enabled:d.stamp,updated_at:new Date().toISOString()}}
async function save(){const d=data();if(!d.recipient||!d.eventName||!d.message){toast('أكمل الجهة والفعالية والنص أولًا');return}localStorage.setItem(RECORDS,JSON.stringify([{...d,savedAt:new Date().toISOString()},...localRecords().filter(x=>x.number!==d.number)].slice(0,100)));setSaveState('جار الحفظ…');try{await cloud(`?on_conflict=client_id,letter_number`,{method:'POST',body:JSON.stringify(payload())});setSaveState('محفوظ سحابيًا');toast('تم حفظ الخطاب في السحابة')}catch(e){setSaveState('محفوظ محليًا',false);toast('تم حفظه محليًا — تعذر الاتصال بالسحابة')}renderRecords()}
async function loadCloud(){try{const rows=await cloud(`?client_id=eq.${encodeURIComponent(clientId)}&order=updated_at.desc&limit=100`);state.records=rows||[];setSaveState('السحابة متصلة')}catch{state.records=[];setSaveState('محلي',false)}}
function renderRecords(){const q=($('#librarySearch')?.value||'').trim().toLowerCase();const local=localRecords().filter(x=>!q||`${x.recipient} ${x.number} ${x.eventName}`.toLowerCase().includes(q));const list=$('#recordsList');if(!local.length){list.innerHTML='<div class="empty">لا توجد خطابات محفوظة بعد</div>';return}list.innerHTML=local.map(x=>`<div class="record"><div class="record-main"><b>${esc(x.recipient||'بدون جهة')}</b><small>${esc(x.number||'')} · ${esc(x.eventName||'')}</small></div><div class="record-actions"><button data-open="${esc(x.number)}">فتح</button><button data-copy="${esc(x.number)}">نسخ</button><button data-delete="${esc(x.number)}">حذف</button></div></div>`).join('')}
function findRecord(n){return localRecords().find(x=>x.number===n)}
function openLibrary(){renderRecords();$('#libraryModal').classList.add('open');$('#libraryModal').setAttribute('aria-hidden','false');$('#librarySearch').focus()}
function closeLibrary(){ $('#libraryModal').classList.remove('open');$('#libraryModal').setAttribute('aria-hidden','true')}
async function copyText(){const d=data();const text=replaceTokens(d.message||'');try{await navigator.clipboard.writeText(text);toast('تم نسخ نص الخطاب')}catch{toast('تعذر النسخ من المتصفح')}}
function print(){window.print()}
function pdf(){const win=window.open('','_blank');if(!win){toast('اسمح بالنوافذ المنبثقة لإخراج PDF');return}const p=$('#paper').cloneNode(true);p.style.transform='none';const css=[...document.querySelectorAll('link[rel=stylesheet]')].map(x=>x.href).join('');win.document.write(`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><link rel="stylesheet" href="${esc(css)}"><style>@page{size:${state.size==='a4'?'A4':'210mm 210mm'};margin:0}body{margin:0;background:#fff}.paper{box-shadow:none!important;transform:none!important}</style></head><body></body></html>`);win.document.close();win.onload=()=>{win.document.body.appendChild(p);setTimeout(()=>win.print(),300)}}
function newLetter(){if(!confirm('بدء خطاب جديد؟ سيتم الاحتفاظ بالخطاب الحالي في المكتبة إذا حفظته.'))return;localStorage.removeItem(STORAGE);fields.forEach(id=>$('#'+id).value='');state.number=number();$('#date').value=today();updateExtra();$('#message').value=defaultMessage();render();toast('تم إنشاء خطاب جديد')}
function bind(){
$('#templateGrid').innerHTML=Object.entries(PAIC_CONTENT.templates).map(([k,t])=>`<button class="template-card" data-template="${k}" style="--card-accent:${k==='sponsorship'?'#1d8b68':k==='partnership'?'#8057c9':k==='invitation'?'#b08a2e':'#397198'}"><span class="mini">${t.icon}</span><b>${t.name}</b><small>${t.eyebrow}</small></button>`).join('');selectTemplate();
$('#templateGrid').addEventListener('click',e=>{const b=e.target.closest('[data-template]');if(!b)return;state.template=b.dataset.template;const old=$('#extraParam').value;selectTemplate();if(!old||Object.values(PAIC_CONTENT.templates).some(t=>t.extraDefault===old))$('#extraParam').value=PAIC_CONTENT.templates[state.template].extraDefault;if(!$('#message').value||confirm('تبديل القالب؟ استبدال النص الحالي بالنص المقترح للقالب الجديد؟'))$('#message').value=defaultMessage();render()});
$$('.size-switch button').forEach(b=>b.addEventListener('click',()=>{state.size=b.dataset.size;selectSize();render()}));
fields.forEach(id=>$('#'+id).addEventListener('input',render));$('#digitalStamp').addEventListener('change',()=>{state.stamp=$('#digitalStamp').checked;render()});
$('#saveBtn').addEventListener('click',save);$('#newBtn').addEventListener('click',newLetter);$('#libraryBtn').addEventListener('click',openLibrary);$$('[data-close]').forEach(b=>b.addEventListener('click',closeLibrary));$('#libraryModal').addEventListener('click',e=>{if(e.target.id==='libraryModal')closeLibrary()});$('#librarySearch').addEventListener('input',renderRecords);
$('#recordsList').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const r=findRecord(b.dataset.open||b.dataset.copy||b.dataset.delete);if(b.dataset.open&&r){fill(r);closeLibrary();toast('تم فتح الخطاب')}if(b.dataset.copy&&r){navigator.clipboard?.writeText(replaceTokens(r.message||''));toast('تم نسخ النص')}if(b.dataset.delete&&r){if(confirm('حذف الخطاب المحفوظ؟')){localStorage.setItem(RECORDS,JSON.stringify(localRecords().filter(x=>x.number!==r.number)));renderRecords();toast('تم حذف الخطاب')}}});
$('#zoomIn').addEventListener('click',()=>{state.zoom=Math.min(1.2,state.zoom+.08);applyPaperScale()});$('#zoomOut').addEventListener('click',()=>{state.zoom=Math.max(.4,state.zoom-.08);applyPaperScale()});$('#fitBtn').addEventListener('click',()=>{const st=$('#paperStage');const w=st.clientWidth-70,h=st.clientHeight-90;const paperW=210*3.7795,paperH=(state.size==='a4'?297:210)*3.7795;state.zoom=Math.max(.4,Math.min(1.05,w/paperW,h/paperH));applyPaperScale()});$('#copyBtn').addEventListener('click',copyText);$('#printBtn').addEventListener('click',print);$('#pdfBtn').addEventListener('click',pdf);
$('#themeBtn').addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem(THEME,document.body.classList.contains('dark')?'dark':'light')});$$('.mobile-tabs button').forEach(b=>b.addEventListener('click',()=>{document.body.classList.toggle('mobile-preview',b.dataset.view==='preview');$$('.mobile-tabs button').forEach(x=>x.classList.toggle('active',x===b));if(b.dataset.view==='preview')setTimeout(()=>$('#fitBtn').click(),50)}));
$('#brandHome').addEventListener('click',e=>{e.preventDefault();window.scrollTo({top:0,behavior:'smooth'})});document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='s'){e.preventDefault();save()}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openLibrary()}if(e.key==='Escape')closeLibrary()});
}
const theme=localStorage.getItem(THEME);if(theme==='dark')document.body.classList.add('dark');bind();seed();loadCloud();
})();
